### ISSUE TITLE
Check if subreddit exists before opening room

### ISSUE THREAD

**Issue by KenavR** [larvalabs/breaker#13]
I don't know if this is considered a bug, but I would suggest checking if a subreddit exists before opening a room for it. I typed some random stuff into the address bar and it created a channel for it. I haven't looked into it on the server, but if people can create rooms without any limits, this could be used maliciously.

**Comment by megamattron** [comment]
Should definitely do this as there's a bunch of junk rooms open now. I'll also write a job to mark existing rooms deleted that aren't valid.
