### ISSUE TITLE
[Request] Mods should be able to delete comments

### ISSUE THREAD

**Issue by KenavR** [larvalabs/breaker#25]
Another Request from Chat, maybe create a reddit account "breakerfeatures" which people can @ in chat with there requests. Breaker seems to get more traction and it will be hard keeping up with the requests. I wouldn't expect people to create a github account.

> CockroachClitoris
> feature request: mods remove comments

**Comment by megamattron** [comment]
This is pretty much supported on the server side, would just need some UI and a websocket message or endpoint for it. Maybe users should be able to delete their own messages too?

**Comment by Keerikkadan91** [comment]
Hi guys, any chance this is coming out soon?

**Comment by megamattron** [comment]
Got a pull request pending for this now @Keerikkadan91 - hopefully will merge soon.

**Comment by megamattron** [comment]
Released.
