### ISSUE TITLE
[Request] Limit number of users in sidebar

### ISSUE THREAD

**Issue by KurtRobo** [larvalabs/breaker#32]
At the moment the sidebar shows a list of users who have logged in. Once there are a large amount of users this may become very large and slow down the browser to fetch the data.

Possibly a something like "Show More" to list more users could help.

**Comment by KenavR** [comment]
@megamattron @rickhanlonii If it is ok with you, I will work on this. 
Features I would add:

- [ ] show only a couple of offline users and as suggested add a "show more" function
- [ ] order the users alphabetical
- [ ] Add a search function that filters the sidebar
- [ ] Maybe add an options to the preferences do hide offline users all together 

Also I believe this is a duplicate from #30

**Comment by megamattron** [comment]
I'm gonna call this done due to PR #30 which is now released.
