### ISSUE TITLE
[Request] Leave #breakerapp

### ISSUE THREAD

**Issue by KenavR** [larvalabs/breaker#36]
Looks like a users gets automatically added to breakerapp even if they leave it on purpose, I think this should be removed.

**Comment by megamattron** [comment]
The idea is that new users should auto join that room, but it must be happening even after they've left the room. So a couple optoins:

1. Add a "deleted" flag to ChatUserRoomJoin and respect that appropriately, and then we would know they had been in the room but left
2. Just check if the user is in any other rooms before auto-adding them to breakerapp chat. If they're in any other rooms they're probably not a new user.
