### ISSUE TITLE
Subreddit Mod Option - Allow all newly created topics to be posted in chat

### ISSUE THREAD

**Issue by cmays90** [larvalabs/breaker#4]
Right now, breakerbot posts when a post becomes the top post for a sub.  On smaller subs, it might also be convenient to have breakerbot post when a new topic is created.

**Comment by megamattron** [comment]
Do you mean on every new submission to the sub?

**Comment by cmays90** [comment]
Yes, on every new submission

**Comment by rickhanlonii** [comment]
This is requested pretty frequently and is actually how the bot originally worked. Definitely a good setting to have.

**Comment by megamattron** [comment]
I'll be releasing this shortly, but just wanted to mention that I'm keeping the same throttling limits that were in place before - so the link bot will only post if it wasn't the last user to post.

**Comment by megamattron** [comment]
This change is now deployed, you can find the preferences in your room settings (if you're a mod):

![room_preferences](https://cloud.githubusercontent.com/assets/408726/15788116/cc621b20-2993-11e6-950f-e9911f50c22c.png)
