### ISSUE TITLE
Unable to @ mention DJ-Professor-K properly

### ISSUE THREAD

**Issue by megamattron** [larvalabs/breaker#42]
In https://www.breakerapp.com/r/bombing

**Comment by KenavR** [comment]
It doesn't work with any dash (-) in the name, this came up a couple of days ago, but I forgot to create an issue.

**Comment by megamattron** [comment]
Must be a regex issue or somethig, I'll try to fix it since it'll make those guys happy. They have another bug open for their flair too: #31
