### ISSUE TITLE
Show warning in UI as user approaches character limit for messages

### ISSUE THREAD

**Issue by megamattron** [larvalabs/breaker#5]
The current message max length is 500, so it'd be nice to warn the user as they're approaching that limit.

This would probably be a good first pull request for someone who wanted to contribute on the frontend.

**Comment by KenavR** [comment]
I believe this issue could be closed or is something missing?

**Comment by megamattron** [comment]
I think this is released, so let's close. Thanks again @KenavR - this is our first officially released PR!
